export const StorageKeys = {
  APP_LANGUAGE: '@APP_LANGUAGE',
  AUTH_DATA: '@AUTH_DATA',
  FCM_KEY: '@FCM_KEY@',
  THEME_MODE: '@THEME_MODE',
  SAVED_USERS: '@SAVED_USERS',
  STATION_ID: '@STATION_ID',
  CART_ID: '@CART_ID',
  CART_COUNT: '@CART_COUNT',
};
